apiVersion: v1
kind: Service
metadata:
  name: marketplace-backend
  namespace: marketplace-staging
  labels:
    app: marketplace-backend
spec:
  type: ClusterIP
  selector:
    app: marketplace-backend
  ports:
    - name: http
      port: 8000
      targetPort: http
