apiVersion: v1
kind: Secret
metadata:
  name: marketplace-backend-secret
  namespace: marketplace-staging
type: Opaque
stringData:
  POSTGRES_USER: "marketplace_user"
  POSTGRES_PASSWORD: "change_me"
  SECRET_KEY: "change_me_super_secret_key"
