apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-frontend
  namespace: marketplace-staging
  labels:
    app: marketplace-frontend
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: marketplace-frontend
  template:
    metadata:
      labels:
        app: marketplace-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/thomassanna/m1de-marketplace-locale-intelligente/frontend:dev-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3
